### ISSUE TITLE
Occasional HTTPError 401 Unauthorized

### ISSUE THREAD

**Issue by c0redumb** [c0redumb/yahoo_quote_download#3]
Occasionally, the urlopen raise HTTPError with 401 Unauthorized response. I don't know what causes it (maybe too much request in a short time?) 

At this time, I tried to catch those exceptions in my calling script and rerun the download after some timed sleep. But this is only a patch solution.

Any suggestions on what causes it?

**Comment by montxero** [comment]
@c0redumb, I think you are right. According to the HTTP/1.1 standard,  [https://tools.ietf.org/html/rfc7235#section-3.1]

>    "The 401 (Unauthorized) status code indicates that the request has not
>     been applied because it lacks valid authentication credentials for
>     the target resource."

I reckon Yahoo has implemented some kind of time out defense against sever overloading and potential ddos attacks by tracking the number / frequency of requests from a specific ip address.

**Comment by montxero** [comment]
Perhaps one way to minimize requests is to keep a local database of  retrieved data. Then when a request is made, the function first checks if the requested data exists on the database and downloads only the necessary data. However this assumes the requests are not due to tests / debugging where you have to hit em up a fair bit.

**Comment by c0redumb** [comment]
I have another code that actually stores historical data, and only pull EOD data for the last few days that is missed. This way the data query and transmission is minimized. However, I still get this kind of unauthorized errors occasionally.

My guess is that the restriction Yahoo put in place might be related to the number of queries, not the amount of data returned. So if I am pulling one-day data for 500 stocks, it is 500 queries. That is the same number of queries as pulling 10-year data for 500 stocks.

**Comment by larryyin** [comment]
I download the whole historical data ticker by ticker with no problem. But if I use multiple threads, it gives error occasionally. So for the same ip, a minimal interval between 2 downloads should be specified. Otherwise yahoo blocks your ip for a period of time.

On May 30, 2017 5:49 PM, c0redumb <notifications@github.com> wrote:

I have another code that actually stores historical data, and only pull EOD data for the last few days that is missed. This way the data query and transmission is minimized. However, I still get this kind of unauthorized errors occasionally.

My guess is that the restriction Yahoo put in place might be related to the number of queries, not the amount of data returned. So if I am pulling one-day data for 500 stocks, it is 500 queries. That is the same number of queries as pulling 10-year data for 500 stocks.

**Comment by c0redumb** [comment]
My code used to do multiple thread (set to 10) concurrent download with the old API. But I found that doesn't work with the new API.

Any more information on the query intervals? 100 per minute per IP?

**Comment by ctpoon** [comment]
Is there anywhere I can modify the useragent?

**Comment by c0redumb** [comment]
> Is there anywhere I can modify the useragent?

https://docs.python.org/3/library/urllib.request.html#urllib.request.Request

**Comment by c0redumb** [comment]
Now claims user agent of Firefox with 9c683a9. Hope that improves the chance for a good response.

**Comment by Fulvioo** [comment]
It appears to me that this error is not due to user agents. 

Here's my try:
- I've built a loop in the _main_ function to catch the error and retry five times (waiting 30secs at each loop), if needed.
- I've then added a function to yqd in order change the user agent (Linux, Mac, Win..) at each of the five loops.

Anyway, in case of unauthorized error the loop continues till the end, but unsuccesfully and always with the same kind of error.
Other ideas?

**Comment by Fulvioo** [comment]
Workaround found !
`import importlib`
and then at each attempt /retry in the loop (in case of error), you need to reload yqd:
`importlib.reload(yqd)`
This shall solve it

**Comment by c0redumb** [comment]
Sorry I haven't touched this for a while. Let me see if I can do something to make it better.

**Comment by c0redumb** [comment]
I think I found a solution, though I still don't know the cause. I suspect the cause is probably a defense mechanism on Yahoo side to throw off massive repeated download.

The solution is to clear the cookiejar before retry the download. In my previous attempts, the retries are done, but implicitly the library sends the same cookie, which results in the same failure.

With that in the code, I am planning to release a v0.9 soon.
