### ISSUE TITLE
javascript api

### ISSUE THREAD

**Issue by ajoposor** [c0redumb/yahoo_quote_download#4]
I'm trying to implement your workaround to obtain data for a web. I could get the crumb and overcome the cross domain limitations through a third party proxy. However I couldn't retrieve the data. Could you provide insights into how to do it or expand your solution for a javascript api?

This is what I've done so far:

// example. 
var url="https://finance.yahoo.com/quote/%5EGSPC/history?p=%5EGSPC";

var cors_api_url = 'https://cors-anywhere.herokuapp.com/';

var requestParameters = {
        method: "GET", //either POST or GET
        url: url
      };

doCORSRequest(requestParameters, function printResult(result) {
	    console.log(result);
	
	var cs = result.indexOf('CrumbStore');
	var cr = result.indexOf('crumb', cs + 10);
	var cl = result.indexOf(':', cr + 5);
	var q1 = result.indexOf('"', cl + 1);
	var q2 = result.indexOf('"', q1 + 1);
	var crumb = result.slice(q1 + 1,q2);
	
	console.log("cs",cs);
	console.log("cr",cr);
	console.log("cl",cl);
	console.log("q1",q1);
	console.log("q2",q2);
	console.log("crumb",crumb);
	
	var url3 ="https://finance.yahoo.com/quote/XLF/history?period1=914299200&period2=1496376000&interval=1d&filter=history&frequency=1d"
	
var url2 = "https://query1.finance.yahoo.com/v7/finance/download/%5EGSPC?period1=1493730135&period2=1496408535&interval=1d&events=history&crumb="+crumb;
	
	console.log(encodeURIComponent(url2));
	
	
var urlGoogleFinance = "https://www.google.com/finance/historical?q=XLY&startdate=2001-12-31&output=csv";
var urlGoogleFinance2 = "https://www.google.com/finance/historical?q=GE&startdate=1990-06-30&output=csv";

var baseUri = "https://query.yahooapis.com/v1/public/yql?q=";
var uriQuery = encodeURIComponent("SELECT * from json where url='"+url3+"'"/*+" and columns='Date,Open,High,Low,Close,Volume' "*/);
var totalUri =  baseUri + uriQuery+"&format=json";

console.log("totalUri", totalUri); 

Plotly.d3.json(totalUri, function(readData) {
			//console.log("readData",readData);
		console.log("readData",readData);
      console.log("readData",readData.query.results.row[0]);
      console.log("readData",readData.query.results);
		});

   });

// main function 
  function doCORSRequest(options, printResult) {
    var x = new XMLHttpRequest();
		console.log(" cors_api_url + options.url", cors_api_url + options.url);
    x.open(options.method, cors_api_url + options.url);
    x.onload = x.onerror = function() {
      printResult(
        options.method + ' ' + options.url + '\n' +
        x.status + ' ' + x.statusText + '\n\n' +
        (x.responseText || '')
      );
    };
    if (/^POST/i.test(options.method)) {
      x.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    }
    x.send(options.data);
  }

**Comment by c0redumb** [comment]
The original idea of my code is pretty simple. Make a query to obtain a matching set of cookie and crumb, then use that in the subsequent downloads.

I haven't done much Javascript myself. Although I do not have time to write the Javascript code for you, I do suggest the following steps to debug your problem.

1. Print or display cookie and crumb after the first query to make sure that you have indeed got back the cookie and crumb (you may want to clear those before the query to make sure that you are getting new ones).
2. For the subsequent downloads, you can print or display the URL to make sure that the same crumb is used (as part of the request URL).
3. You may want to check that the correct cookie is used. I am guessing that might be your problem because you used a proxy, but I am not sure. A cookie is always associated to a URL (the cookie is associated with .yahoo.com in this case), and it is only sent for subsequent request to that URL.

Hope it helps.

**Comment by ajoposor** [comment]
Thank you for taking the time to respond. I'll follow your suggestions. I'm quite novice on this, but I'll give it a try.

**Comment by ajoposor** [comment]
I'm missing the cookie part. I have to find out how to get it and send it using js.

**Comment by c0redumb** [comment]
Usually the cookie is handled automatically by the browser (I assumed that your js code is running by a browser). I am not sure how it works when you use a proxy.

**Comment by c0redumb** [comment]
I will close this issue, as it is not related to the main functionality of the code.
